version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest  # Specify version here or leave it latest
    container_name: qdrant_service
    ports:
      - "6333:6333"  # Exposing Qdrant's default port
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__API_KEY=th3s3cr3tk3y
      - QDRANT__SERVICE__GRPC_PORT="6334"
      - QDRANT__SERVICE__HTTP_PORT="6333"

  ollama:
    image: ollama/ollama:latest
    container_name: ollama_service
    ports:
      - "11434:11434"  # Exposing Ollama's default port
    environment:
      - OLLAMA_PORT=11434  # Set Ollama's default port

volumes:
  qdrant_data:
    driver: local
